services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
      # - ./src/.env
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db_postgres:5432/taller_db
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    depends_on:
      - db
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=taller_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
     - 5432:5432

volumes:
  postgres-data:
